### ISSUE TITLE
typeahead is not function errors when using jquery 3.x

### ISSUE THREAD

**Issue by viktor-rachuk** [twitter/typeahead.js#1697]

**Comment by ghost** [comment]
In my case is =>
Uncaught TypeError: this.transport is not a function
    at Prefetch.fromNetwork (typeahead.bundle.js:596)
    at Bloodhound.loadPrefetch [as _loadPrefetch] (typeahead.bundle.js:844)
    at Bloodhound.initialize [as _initialize] (typeahead.bundle.js:859)
    at Bloodhound.initialize (typeahead.bundle.js:866)
    at new Bloodhound (typeahead.bundle.js:817)

**Comment by ghost** [comment]
Finally figured it out !
It's not jquery 3x ... it's jquery 3x slim.

**Comment by kamilwylegala** [comment]
@viktor-rachuk Apparently this repository is not maintained anymore.

I switched to fork: https://github.com/corejavascript/typeahead.js

Works fine. No code changes are required after updating jQuery to 3.* except:
```
require("corejs-typeahead");
```
